name: deploy dist files

on:
  workflow_call:
    inputs:
      # "host" is the name of the host where to copy the distribution artifact
      host:
        required: true
        type: string
      # "username" is the name of the user with whom the dist files should be copied
      username:
        required: true
        type: string
      # "distname" is the name of the distribution artifact to copy
      distname:
        required: true
        type: string
      # "target" is the target folder on the host where to copy the distribution artifact
      target:
        required: true
        type: string

jobs:
  deploy-dist:
    runs-on: ubuntu-22.04
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.distname }}
          path: dist

      - name: List dist files
        run: ls dist

      - name: Copy dist files to ${{ inputs.host }} server to folder ${{ inputs.target }}
        uses: appleboy/scp-action@master
        with:
          host: ${{ inputs.host }}
          username: ${{ inputs.username }}
          key: ${{ secrets.TREIBTOFF21_SSH_PRIVATE_KEY }}
          source: "dist/"
          strip_components: 1
          rm: true
          target: ${{ inputs.target }}
