name: deploy dist files

on:
  workflow_call:
    inputs:
      host:
        required: true
        type: string

jobs:
  deploy-dist:
    runs-on: ubuntu-22.04
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: salvation-dist
          path: dist

      - name: List dist files
        run: ls dist

      - name: Copy dist files to ${{ inputs.host }} server
        uses: appleboy/scp-action@master
        with:
          host: ${{ inputs.host }}
          username: falcon
          key: ${{ secrets.TREIBTOFF_SSH_PRIVATE_KEY }}
          source: "dist/"
          strip_components: 1
          rm: true
          target: "/var/www/html/salvation"
